import type { Metadata } from "next";
import { Poppins } from "next/font/google";

import "@/_shared/style/globals.css";

import Header from "@/_shared/ui/Header";

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "outfit album",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppins.variable} flex justify-center bg-gray-100 antialiased`}
      >
        <div className="flex h-screen w-screen max-w-[1024px] flex-col bg-white">
          <Header name="OUTFIT" />
          <div className="h-full w-full px-4">{children}</div>
        </div>
      </body>
    </html>
  );
}
